#pragma once
#include <QMainWindow>
#include <QOpenGLWidget>
#include <QTimer>
#include <QDomDocument>
#include <QVTKOpenGLNativeWidget.h>
#include <QColorDialog>
#include <QFile>

#include <vtkCamera.h>
#include <vtkRenderWindow.h>
#include <vtkRenderer.h>
#include <vtkSphereSource.h>
#include <vtkConeSource.h>
#include <vtkTransform.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkCylinderSource.h>
#include <vtkNamedColors.h>
#include <vtkPolyDataMapper.h>
#include <vtkProperty.h>
#include <vtkFollower.h>
#include <vtkLineSource.h>
#include <vtkTexture.h>
#include <vtkPNGReader.h>
#include <vtkImageFlip.h>
#include <vtkPlaneSource.h>
#include <vtkCallbackCommand.h>
#include <vtkCellData.h>
#include <vtkLine.h>
#include <vtkXMLPolyDataWriter.h>
#include <vtkPolyLine.h>
#include <vtkAssembly.h>
#include <vtkPolygon.h>
#include <vtkOBJImporter.h>
#include <vtkOBJReader.h>

#include <Eigen/Core>
#include <Eigen/Dense>

#include <algorithm>
#include <filesystem>